name: benchmarking-web
channels:
  - conda-forge
dependencies:
  - python=3.8
  - aiohttp
  - aiohttp-jinja2
  - gunicorn
  - click
  - bs4
  - pytest
  - pytest-aiohttp
  - pytest-cov
  - codecov
  - pip
  - pip:
    - motor
    - dnspython
    - mockupdb
